from typing import Any
import numpy as np #type:ignore
import pandas as pd #type: ignore
import zarr #type: ignore
from scipy.ndimage import label, find_objects, gaussian_filter, median_filter #type:ignore
from scipy.optimize import curve_fit #type:ignore
from skimage.feature import peak_local_max #type:ignore
from skimage.segmentation import watershed #type:ignore
from skimage.measure import regionprops #type:ignore

import torch #type:ignore
import torch.nn as nn #type:ignore
from torch.amp import autocast #type:ignore

import os, time, datetime, logging, argparse, json, math, sys, shutil
from copy import deepcopy

SEP = os.sep


class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NumpyEncoder, self).default(obj)


# ----------------------------
def setup_logging(resultDir):
    """Setup logging configuration with timestamped log file
    Args:
        midas_layer_dir (str): Path to the MIDAS layer directory
    Returns:
        logger (logging.Logger): Logger object for logging messages
    """

    log_dir = f"{resultDir}SR_out{SEP}"
    if os.path.exists(log_dir):
        shutil.rmtree(log_dir)
    os.makedirs(log_dir)
    
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    log_filepath = f"{log_dir}SR_logs_{timestamp}.log"
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(message)s',
        handlers=[
            logging.FileHandler(log_filepath),
            logging.StreamHandler()
        ]
    )
    
    logger = logging.getLogger(__name__)
    logger.info(f"Logging initialized for super-resolution workflow. Log filepath: {log_filepath}")
    return logger

    
# ----------------------------
def read_hkls_csv(hkls_csv_path):
    """Read the hkls.csv file generated by MIDAS and return it as a pandas dataframe
    Args:
        hkls_csv_path (str): path to the hkls.csv file
    Returns:
        df_hkls (pandas dataframe): dataframe with the hkls.csv file
    """

    df_hkls = pd.read_csv(hkls_csv_path, sep=' ')
    return df_hkls


# ----------------------------
def create_rotation_matrices(tx, ty, tz):
    """
    Create the rotation matrices for the given rotation angles
    Args:
        tx (float): rotation about x-axis in degrees
        ty (float): rotation about y-axis in degrees
        tz (float): rotation about z-axis in degrees
    Returns:
        Rx (np.ndarray): rotation matrix about x-axis
        Ry (np.ndarray): rotation matrix about y-axis
        Rz (np.ndarray): rotation matrix about z-axis
    """

    Rx = np.array([
        [1, 0, 0],
        [0, np.cos(np.deg2rad(tx)), -np.sin(np.deg2rad(tx))],
        [0, np.sin(np.deg2rad(tx)), np.cos(np.deg2rad(tx))]
        ])

    Ry = np.array([
        [np.cos(np.deg2rad(ty)), 0, np.sin(np.deg2rad(ty))],
        [0, 1, 0],
        [-np.sin(np.deg2rad(ty)), 0, np.cos(np.deg2rad(ty))]
        ])

    Rz = np.array([
        [np.cos(np.deg2rad(tz)), -np.sin(np.deg2rad(tz)), 0],
        [np.sin(np.deg2rad(tz)), np.cos(np.deg2rad(tz)), 0],
        [0, 0, 1]
        ])

    return Rx, Ry, Rz


# ----------------------------
def create_distortion_map(RR, EE, p0, p1, p2, p3, px):
    """
    Create the distortion map for the given parameters
    Args:
        RR (np.ndarray): radial map (in microns)
        EE (np.ndarray): polar angle map (spans from 180 to -180 degrees in clockwise direction)
        p0 (float): distortion parameter
        p1 (float): distortion parameter
        p2 (float): distortion parameter
        p3 (float): distortion parameter
        px (float): pixel size in microns
    Returns:
        R_N (np.ndarray): normalized radial map in microns
    """

    RR_N = RR / np.max(RR) # Normalized radial map
    EE_T = 90 - EE # Transformed polar angle map

    # Distortion terms
    dist_gRE = p0 * (RR_N**2) * np.cos(np.deg2rad(2*EE_T)) # 2-fold angular
    dist_hRE = p1 * (RR_N**4) * np.cos(np.deg2rad(4*EE_T + p3)) # 4-fold angular
    dist_kRE = p2 * (RR_N**2) # radial distortion
    dist_fRE = 1 + dist_gRE + dist_hRE + dist_kRE # combined distortion factor

    return dist_fRE


# ----------------------------
class CNNSR(torch.nn.Module):
    """CNN model class for super-resolution
    """

    def __init__(self, l_ch_nrs, l_ker_size, l_act_func, X_channels):
        """Initializaion function of the class; runs automatically when class is created
        Args:
            l_ch_nrs (list of int): list with number of channels in each successive CNN layer
            l_ker_size (list of odd int): list with kernel size for each successive CNN layer
            l_act_func (list of str): list with activation function ('r', 's', 'lr', 't') each successive CNN layer
            X_channels (int): no. of channels in input X data
        """

        super(CNNSR, self).__init__()

        self.cnn_ops = []
        cnn_out_chs = tuple(l_ch_nrs)
        cnn_in_chs = (X_channels, ) + cnn_out_chs[:-1]

        for (in_ch, out_ch, ker_sz, act_func) in zip(
            cnn_in_chs, cnn_out_chs, l_ker_size, l_act_func):

            # Add convolution layer
            pad_sz = int(ker_sz / 2)
            self.cnn_ops += [
                torch.nn.Conv2d(in_channels=in_ch, out_channels=out_ch,\
                               kernel_size=ker_sz, padding=pad_sz)
            ]

            # Add activation layer
            if act_func == "r": self.cnn_ops += [torch.nn.ReLU()]
            if act_func == "s": self.cnn_ops += [torch.nn.Sigmoid()]
            if act_func == "lr": self.cnn_ops += [torch.nn.LeakyReLU()]
            if act_func == "t": self.cnn_ops += [torch.nn.Tanh()]

        self.cnn_layers = torch.nn.Sequential(*self.cnn_ops)

    def forward(self, x):

        _out = x
        for layer in self.cnn_layers:
            _out = layer(_out)

        return (_out)
    

# ----------------------------
def load_trained_CNNSR(midasVerDir, mod_dir, mod_itr, torch_devs):
    """ loads trained CNNSR model based on input directory and iteration.\
    NOTE: The model directory should contain the following files:
        - mod-it{mod_itr}.pth: model weights
        - _train_args.json: model training arguments
    Args:
        midasVerDir (str): directory containing the MIDAS version. This is the directory that contains the trained models.
        mod_dir (str): directory containing the trained model
        mod_itr (int): model iteration
        torch_devs (torch.device): device to be used for loading model
    Returns:
        mod (torch model): loaded model instance with weights
        mod_args (dict): arguments used for model training
        X_channels (list): channels used in input data for model (0-Intensity, 1-Radius, 2-Eta)
    """
    
    mod_args_filepath = f"{midasVerDir}{SEP}{mod_dir}{SEP}_train_args.json"
    with open(mod_args_filepath, 'r') as f:
        mod_args = json.load(f)

    X_channels = [0]
    if mod_args["useRch"] in ["True", "true", True, "Yes", "yes", "Y", "y"]:
        X_channels.append(1)
    if mod_args["useEtach"] in ["True", "true", True, "Yes", "yes", "Y", "y"]:
        X_channels.append(2)

    in_ch = len(X_channels)
    
    mod_itr_path = f"{midasVerDir}{SEP}{mod_dir}{SEP}mod-it{mod_itr}.pth"

    l_layer_params = mod_args["arch"].split("_")
    l_ch_nrs = [int(i.split("-")[0]) for i in l_layer_params]
    l_ker_size = [int(i.split("-")[1]) for i in l_layer_params]
    l_act_func = [str(i.split("-")[2]) for i in l_layer_params]

    mod = CNNSR(l_ch_nrs, l_ker_size, l_act_func, in_ch)
    mod = nn.DataParallel(mod)
    mod.load_state_dict(torch.load(mod_itr_path, map_location=torch_devs, weights_only=True))
    mod = mod.to(torch_devs)

    return (mod, mod_args, X_channels)


def ringNr_map_on_detector(sr_params):
    """ Create the ring number map on the detector. Pixels that don't belong to any ring are marked with -1.
    Pixels that belong to a ring in sr_params["ringsToUse"] are marked with the ring index (starting from 0).
    Args:
        numPxY (int): number of pixels in the Y direction (horizontal direction)
        numPxZ (int): number of pixels in the Z direction (vertical direction)
        sr_params (dict): dictionary containing the parameters for the super-resolution process
    Returns:
        RingNrmap (arr): ring number map on the detector
    """

    det_shape = (sr_params["numPxZ"], sr_params["numPxY"])

    # YY and ZZ are the pixel coordinates of the detector
    # These are relative to the top left corner pixel as origin
    YYpx, ZZpx = np.meshgrid(np.arange(0, sr_params["numPxY"]), np.arange(0, sr_params["numPxZ"]))

    # yyd and zzd are the physical coordinates of the detector in microns
    # These are relative to the beam center as origin
    yyd = (-YYpx + sr_params["Ypx_BC"])*sr_params["pxSize"]
    zzd = (ZZpx - sr_params["Zpx_BC"])*sr_params["pxSize"]

    # xyz_comb is the combined array of x, y, z physical coordinates of the detector in microns
    # The detector map here is flattened; first row is x, second row is y, third row is z coordinates of all pixels
    xyz_comb = np.array([
        np.zeros_like(yyd.flatten()),
        yyd.flatten(),
        zzd.flatten()
    ])

    # Create the rotation matrices
    Rx, Ry, Rz = create_rotation_matrices(sr_params["tx"], sr_params["ty"], sr_params["tz"])

    # xyz_comb_rot is the combined array of x, y, z physical coordinates of the detector in microns after rotation
    xyz_comb_rot = (Rx @ (Ry @ Rz)) @ xyz_comb

    # X, Y, Z are the cartesian lab coordinates of the detector in microns
    XX = (sr_params["Lsd"] + xyz_comb_rot[0]).reshape(det_shape)
    YY = xyz_comb_rot[1].reshape(det_shape)
    ZZ = xyz_comb_rot[2].reshape(det_shape)

    RR = (sr_params["Lsd"]/XX) * np.sqrt(YY**2 + ZZ**2)
    EE = np.zeros_like(YY)
    EE[YY <= 0] = np.rad2deg(np.arccos(ZZ[YY<=0] / (np.sqrt(YY[YY<=0]**2 + ZZ[YY<=0]**2))))
    EE[YY > 0] = np.rad2deg(- np.arccos(ZZ[YY>0] / (np.sqrt(YY[YY>0]**2 + ZZ[YY>0]**2))))

    # Create the distortion map
    dist_fRE = create_distortion_map(RR, EE,
                                    sr_params["p0"], sr_params["p1"], sr_params["p2"], sr_params["p3"],
                                    sr_params["pxSize"])

    Rmap = RR * dist_fRE / sr_params["pxSize"]

    # 2. Create frame_RingNrmap
    # Initialize with -1 to represent pixels that do not belong to any ring
    RingNrmap = np.full(det_shape, -1, dtype=int)

    for i, R in enumerate(sr_params["rings_to_use_Rpx"]):
        # Mask for pixels within the allowed deviation of the current ring radius
        ring_mask = np.abs(Rmap - R) <= (sr_params["ring_width"]/sr_params["pxSize"])
        RingNrmap[ring_mask] = i

    return (RingNrmap)


# ----------------------------
def patches_from_detector_frame(frame_goodCoords, sr_config, connectivity_dim=8):
    """ extracts patches from input detector frame using connected component algorithm. First a labelled array is created where different spots\
    are marked with different label. Each spot is then isolated and pasted onto a patch of size=patch_size such that the max intensity pixel is\
    at the center of the patch.
    Args:
        frame_goodCoords (arr): experimental detector frame with good pixels (pixels that belong to a ring and exceed the threshold for that ring)
        sr_config (dict): dictionary containing the configuration for the super-resolution process
        connectivity_dim (int; default=8): if set to 8: it accepts continuity with diagonal cells; otherwise it uses 4-connectivity only
    Returns:
        patches (arr): extracted patch array (N,patch_size,patch_size)
        patches_Z00 (list of int): Z coordinates of (0,0) pixels in patches
        patches_Y00 (list of int): Y coordinates of (0,0) pixels in patches
        nr_pixels_in_patch (list of int): no. of non-zero pixels in the patch
    """

    patch_size = sr_config["spot_find_args"]["patch_size"]

    # Label connected regions in the binary mask
    if connectivity_dim in [8, 8.0, "8"]:
        # Define an 8-connectivity structure that includes diagonals
        structure = np.array([[1, 1, 1],
                              [1, 1, 1],
                              [1, 1, 1]])

        labeled_array, num_features = label(frame_goodCoords, structure)
        
    else:
        labeled_array, num_features = label(frame_goodCoords) # uses 4-connectivity

    # Find bounding boxes for each labeled region
    bounding_boxes = find_objects(labeled_array)
    
    # Extract and store only the region corresponding to each spot
    spots = []
    patches = []
    patches_Y00, patches_Z00 = [], []
    nr_pixels_in_patch = []

    for i, bbox in enumerate(bounding_boxes):
        if bbox is not None:  # Ensure there is a valid region
            # Extract the sub-array corresponding to the current spot
            spot = frame_goodCoords[bbox]

            # Mask out values not belonging to the current spot
            spot = np.where(labeled_array[bbox] == (i + 1), spot, 0)
            nr_pixels_in_spot = np.count_nonzero(spot)
            
            if nr_pixels_in_spot >= sr_config["minPxCount"]:

                # Find the row, col position of the maximum intensity pixel within the spot
                r_max_spot, c_max_spot = np.unravel_index(np.argmax(spot), spot.shape)  # (row, col)
                Zpx_max_spot = bbox[0].start + r_max_spot
                Ypx_max_spot = bbox[1].start + c_max_spot

                Z00_patch = Zpx_max_spot - int(patch_size/2)
                Y00_patch = Ypx_max_spot - int(patch_size/2)

                # If Z00 and Y00 are such that cropped region will be within frame boundaries
                if (Z00_patch >= 0) and \
                    (Z00_patch < frame_goodCoords.shape[0] - patch_size) and \
                    (Y00_patch >= 0) and \
                    (Y00_patch < frame_goodCoords.shape[1] - patch_size):

                    # Create patch by padding the spot on all sides to ensure it can be cropped properly
                    patch = np.pad(spot, pad_width=patch_size, mode='constant', constant_values=0)
                    
                    # Find the row, col position of the maximum intensity pixel within the patch
                    r_max_patch, c_max_patch = np.unravel_index(np.argmax(patch), patch.shape)  # (row, col)

                    # Crop the patch such that max int pixel will be at center of patch
                    rs = int(r_max_patch - int(patch_size/2))
                    cs = int(c_max_patch - int(patch_size/2))
                    rf, cf = rs + patch_size, cs + patch_size
                    patch = patch[rs:rf, cs:cf]
                    patches.append(patch)

                    patches_Z00.append(Z00_patch)
                    patches_Y00.append(Y00_patch)

                    spots.append(spot)
                    nr_pixels_in_patch.append(np.count_nonzero(spot))


    patches = np.array(patches)

    return (patches, patches_Z00, patches_Y00, nr_pixels_in_patch)


# ----------------------------
def weighted_center_of_mass(patch, threshold=0.5):
    """ Computes the weighted center of mass (centroid) of a 2D patch.
    Args:
        patch (ndarray): 2D NumPy array representing the patch.
    Returns:
        tuple: (Z_center, Y_center) coordinates of the centroid.
            Z represents row, Y represents col
    """

    # Ensure the patch is a NumPy array
    patch = np.array(patch)
    patch[patch < threshold*np.max(patch)] = 0

    # Get the dimensions of the patch
    height, width = patch.shape

    # Generate coordinate grids
    Z_indices, Y_indices = np.indices((height, width))

    # Compute the total mass (sum of all pixel intensities)
    total_mass = np.sum(patch)

    # Avoid division by zero
    if total_mass == 0:
        Y_center, Z_center = width / 2, height / 2

    else:
        # Compute the weighted sums
        Y_center = np.sum(Y_indices * patch) / total_mass
        Z_center = np.sum(Z_indices * patch) / total_mass

    com_coords = (Z_center, Y_center)
    
    return com_coords


# ----------------------------
def com_peak_coords(patch, locmax_peak_coords, threshold=0.5, peak_crop_size=20):
    """ Calculate center of mass peak coordinates in a patch.
    Args:
        patch (arr): input patch (with single or multiple peaks)
        locmax_peak_coords (arr): peak coords obtained from local maxima
        threshold (float; default=0.5): a fraction value to threshold cropped peak patches
        peak_crop_size (int): size of peak patches that are cropped around each local max peak position.
            center of mass calculation is done in the cropped patch
    Returns:
        com_peak_coord (arr): array with com peak coordinates; column0 has Z (row) coordinates, column1 has Y (column) coordinates
    """
    
    n_locmax_peaks = len(locmax_peak_coords)
    com_peakY, com_peakZ = [], []

    for i in range(0, n_locmax_peaks):

        # Y00 & Z00 positions below are (0,0) px position of cropped peak patch from the full patch
        # These are NOT the Y00 & Z00 positions of the patch wrt detector coordinate frame
        peak_patch_Y00 = locmax_peak_coords[i][1] - int(peak_crop_size/2)
        peak_patch_Z00 = locmax_peak_coords[i][0] - int(peak_crop_size/2)
        
        row_T, row_B = max(0,peak_patch_Z00), min(peak_patch_Z00 + peak_crop_size, patch.shape[0])
        col_L, col_R = max(0,peak_patch_Y00), min(peak_patch_Y00 + peak_crop_size, patch.shape[1])
        
        peak_patch = patch[row_T:row_B, col_L:col_R]
        Z_center, Y_center = weighted_center_of_mass(peak_patch, threshold)

        com_peakY.append(peak_patch_Y00+Y_center)
        com_peakZ.append(peak_patch_Z00+Z_center)

    com_peak_coords = np.zeros(shape=(n_locmax_peaks,2))
    com_peak_coords[:,0] = np.array(com_peakZ)
    com_peak_coords[:,1] = np.array(com_peakY)

    return (com_peak_coords)


# ----------------------------
def watershed_peaks(patch, peak_coords, mask_thresh):
    """Apply watershed algorithm to allocate regions 
    Args:
        patch (arr): input patch
        peak_coords (arr): coordinates of peaks in patch
        mask_thresh (float): fraction of max intensity used as threshold for mask
    Returns:
        labelled_patch (arr): labelled patch
        peak_label_values (arr): label values of peaks
        peaks_Isum (arr): sum of intensities of peaks
    """

    n_peaks_in_patch = len(peak_coords)
    # Create markers for watershed algorithm
    markers = np.zeros_like(patch, dtype=np.int32)
    for i in range(n_peaks_in_patch):
        markers[peak_coords[i][0], peak_coords[i][1]] = i + 1

    # Apply watershed with a mask
    mask_thresh = mask_thresh * np.max(patch)
    labelled_patch = watershed(-patch, markers, mask=patch>mask_thresh)

    # Get properties of labelled regions
    label_props = regionprops(labelled_patch, intensity_image=patch)
    peak_label_values = [prop.label for prop in label_props]
    peaks_Isum = [prop.mean_intensity * prop.area for prop in label_props]
    peaks_NrPixels = [prop.num_pixels for prop in label_props]


    return (labelled_patch, peak_label_values, peaks_Isum, peaks_NrPixels)


# ----------------------------
def multi_pv_fit(patch, Y00, Z00, Ypx_BC, Zpx_BC, lrsz, srfac, min_distance, threshold_rel, gauss_filter_sigma=0, median_filter_size=1, lr_int_thresh=10.0):
    """ performs multiple pseduo-voigt fit on input patch. No. of peaks and their approx location is identified using "loc_max_coords"
    Args:
        patch (arr): input patch (with single or multiple peaks)
        Y00 (int): Y coord of (0,0) px of patch in detector frame in native x1 resolution
        Z00 (int): Z coord of (0,0) px of patch in detector frame in native x1 resolution
        Ypx_BC (float): Beam center Y coord in detector frame
        Zpx_BC (float): Beam center Z coord in detector frame
        lrsz (int): low-res native patch size
        srfac (int): super-res factor of patch being fitted
        min_distance (float): minimum distanc (in pixels) between two peaks
        threshold_rel (float): threshold value to count a pixel as a peak
        gauss_filter_sigma (float; default=1): standard deviation for Gaussian kernel
        median_filter_size (float; default=1): size that is taken from the input array\
            at every element position, to define input to the filter function
        lr_int_thresh (float; default=10.0): threshold used to filter out pixels
    Returns:
        fit_peaks (dict): dictionary with properties of fitted peaks; the peak positions here are in detector frame coordinates
        fit_peak_coords (arr): array with pv-fit peak coordinates; column0 has Z (row) coordinates, column1 has Y (column) coordinates;\
            the peak positions here are in patch coordinates
        fit_patch (arr): fitted patch
    """

    # Threshold int for SRx patch
    SRx_thresholdInt = lr_int_thresh / (srfac * srfac)

    def multiPV2d_diffLGwidth(RE_coords, *params):
        RR, EE = RE_coords
        n_paramsPerPeak = 8
        n_peaks = len(params) // n_paramsPerPeak
        patchI = np.zeros_like(RR, dtype=np.float32)
        
        for i in range(n_peaks):
            Rpx, EtaDeg, sigGR, sigGEta, sigLR, sigLEta, LGmix, IMax = params[i * n_paramsPerPeak : (i + 1) * n_paramsPerPeak]
            G = IMax * np.exp(-0.5 * ((RR - Rpx) / sigGR)**2 - 0.5 * ((EE - EtaDeg) / sigGEta)**2)
            L = IMax * 1 / ((1 + ((RR - Rpx) / sigLR)**2) * (1 + ((EE - EtaDeg) / sigLEta)**2))
            patchI += (LGmix * L) + ((1 - LGmix) * G)
        
        patchI[patchI<SRx_thresholdInt] = 0

        return (patchI)

    def multiPV2d_diffLGwidth_forFit(RE_coords, *params):
        patchI = multiPV2d_diffLGwidth(RE_coords, *params)
        return (patchI.ravel())


    # Set parameter bounds to constrain the fit
    dR, dEta, dIMax= 2, 0.1, 400/srfac # R and Eta change allowed from initial estimate

    # Create RR and EE spread over the patch
    dpx_sr = 1 / srfac # pixel step size in super-res patch

    # Y-Z coordinate values
    Ypx = np.arange(Y00, Y00 + lrsz, dpx_sr)
    Zpx = np.arange(Z00, Z00 + lrsz, dpx_sr)

    # Create meshgrids of Radius and Eta values
    grid_YY, grid_ZZ = np.meshgrid(Ypx, Zpx)
    grid_RR = ((Ypx_BC - grid_YY)**2 + (Zpx_BC - grid_ZZ)**2)**0.5
    grid_EE = np.rad2deg(np.arccos((grid_ZZ - Zpx_BC) / grid_RR))
    # Convert Eta_inDeg to -ve where Ypx < Ypx_BC
    grid_EE = grid_EE * ((grid_YY - Ypx_BC) / np.abs(grid_YY - Ypx_BC))

    # Apply Gaussian and median filters to the patch for peak finding
    patch_for_locmax = gaussian_filter(patch, sigma=gauss_filter_sigma)
    patch_for_locmax = median_filter(patch_for_locmax, size=median_filter_size)

    # Find local maxima coords in the filtered patch
    locmax_coords = peak_local_max(patch_for_locmax, min_distance=min_distance, threshold_rel=threshold_rel)

    nPeaks_locmax = len(locmax_coords)
    locmax_Y, locmax_Z = locmax_coords[:,1], locmax_coords[:,0]

    fit_params_names = ["R(px)", "Eta(deg)", "SigGR", "SigGEta", "SigLR", "SigLEta", "LGmix", "IMax"]

    init_guess = [0, 0, 0.3, 0.3, 0.3, 0.3, 0.5, 0] * nPeaks_locmax
    lower_bounds = [0, 0, 0.1, 0.05, 0.1, 0.05, 0, 0] * nPeaks_locmax
    upper_bounds = [0, 0, 3.0, 3.0, 3.0, 3.0, 1, 0] * nPeaks_locmax

    n_paramsPerPeak = len(fit_params_names)

    # Iterate over each locmax peak identified
    for i in range(nPeaks_locmax):
        Rpx_guess, Eta_guess = grid_RR[locmax_Z[i], locmax_Y[i]], grid_EE[locmax_Z[i], locmax_Y[i]]
        IMax_guess = patch[locmax_Z[i], locmax_Y[i]]

        # Update initial guess and bounds of Radius
        init_guess[i * n_paramsPerPeak] = Rpx_guess
        lower_bounds[i * n_paramsPerPeak] = Rpx_guess - dR
        upper_bounds[i * n_paramsPerPeak] = Rpx_guess + dR

        # Update initial guess and bounds of Eta
        init_guess[i * n_paramsPerPeak + 1] = Eta_guess
        lower_bounds[i * n_paramsPerPeak + 1] = Eta_guess - dEta
        upper_bounds[i * n_paramsPerPeak + 1] = Eta_guess + dEta

        # Update initial guess and bounds of IMax
        init_guess[i * n_paramsPerPeak + 7] = IMax_guess
        upper_bounds[i * n_paramsPerPeak + 7] = IMax_guess + dIMax


    popt, pcov = curve_fit(multiPV2d_diffLGwidth_forFit, (grid_RR, grid_EE), patch.ravel(), p0=init_guess, bounds=(lower_bounds, upper_bounds),
            maxfev=1000,  # Increase the number of function evaluations if needed
            method="trf")
    
    fit_patch = multiPV2d_diffLGwidth((grid_RR, grid_EE), *popt).reshape(grid_RR.shape)

    fit_peaks = [] # list to store dictionaries with peak properties
    for i in range(nPeaks_locmax):
        params = popt[i*n_paramsPerPeak:(i+1)*n_paramsPerPeak]
        fit_peaks.append({fit_params_names[j]:params[j] for j in range(0, n_paramsPerPeak)})

        # Get Y-Z coordinates from R-Eta
        Y0_fit = Ypx_BC + (fit_peaks[i]['R(px)'] * np.sin(np.deg2rad(fit_peaks[i]['Eta(deg)'])))
        Z0_fit = Zpx_BC + (fit_peaks[i]['R(px)'] * np.cos(np.deg2rad(fit_peaks[i]['Eta(deg)'])))

        fit_peaks[i]['Y(px)'] = Y0_fit
        fit_peaks[i]['Z(px)'] = Z0_fit

    fit_peak_coords = np.zeros(shape=(len(fit_peaks),2))
    fit_peak_coords[:,0] = np.array([fit_peaks[i]['Z(px)'] for i in range(0, len(fit_peak_coords))])
    fit_peak_coords[:,1] = np.array([fit_peaks[i]['Y(px)'] for i in range(0, len(fit_peak_coords))])

    fit_peak_coords[:,0] = (fit_peak_coords[:,0] - Z00) * srfac
    fit_peak_coords[:,1] = (fit_peak_coords[:,1] - Y00) * srfac


    return fit_peaks, fit_peak_coords, fit_patch


# ----------------------------
def pseudoVoigt2d_diffLGwidth(yy, zz, y0, z0, ySigG, zSigG, ySigL, zSigL, LGmix, IMax, *args):
    """create 2D pseudo-voigt spread over yy and zz coordinates using different gaussian and lorentzian widths
    Args:
        yy (arr): Y coord (pixel) grid array that maps Y distribution over patch
        zz (arr): Z coord (pixel) grid array that maps Y distribution over patch
        y0 (float): Peak position Y coord (pixel)
        z0 (float): Peak position Z coord (pixel)
        ySigG (float): Gaussian peak width in Y-axis
        zSigG (float): Gaussian peak width in Z-axis
        ySigL (float): Lorentzian peak width in Y-axis
        zSigL (float): Lorentzian peak width in Z-axis
        LGmix (float): LGmix factor
        IMax (float): Max intensity
        *args (list): [rot_deg (rotation angle in degrees)]
    Returns:
        PV (arr): pseudo-Voigt peak over Y-Z grid
    """


    # ----------------------------
    def gaussian2d(yy, zz, y0, z0, ySig, zSig, IMax, *args):
        """create 2D Gaussian spread over yy and zz coordinates
        """

        if len(args) > 0: rot_deg = args[0]
        else: rot_deg = 0

        rot_rad = np.deg2rad(rot_deg) # degree to radian

        # Rotate coordinates
        yyRot = (yy - y0) * np.cos(rot_rad) - (zz - z0) * np.sin(rot_rad)
        zzRot = (yy - y0) * np.sin(rot_rad) + (zz - z0) * np.cos(rot_rad)

        # Create gaussian distribution
        G = IMax * np.exp(-0.5 * (yyRot / ySig)**2 - 0.5 * (zzRot / zSig)**2)

        return (G)


    # ----------------------------
    def lorentzian2d(yy, zz, y0, z0, ySig, zSig, IMax, *args):
        """create 2D Lorentzian spread over yy and zz coordinates
        """

        if len(args) > 0: rot_deg = args[0]
        else: rot_deg = 0

        rot_rad = np.deg2rad(rot_deg) # degree to radian

        # Rotate coordinates
        yyRot = (yy - y0) * np.cos(rot_rad) - (zz - z0) * np.sin(rot_rad)
        zzRot = (yy - y0) * np.sin(rot_rad) + (zz - z0) * np.cos(rot_rad)

        # Create lorentzian distribution
        L = IMax * 1 / ((1 + (yyRot / ySig)**2) * (1 + (zzRot / zSig)**2))

        return (L)


    if len(args) > 0: rot_deg = args[0]
    else: rot_deg = 0

    # Create gaussian and lorentzian distributions
    G = gaussian2d(yy, zz, y0, z0, ySigG, zSigG, IMax, *[rot_deg])
    L = lorentzian2d(yy, zz, y0, z0, ySigL, zSigL, IMax, *[rot_deg])
    
    # Create pseudo-voigt distribution
    PV = (LGmix * L) + ((1 - LGmix) * G) # pseudo-voigt 2d

    return (PV)


# ----------------------------
def parse_sr_config_txt(SRconfig_path):
    """Parse the SR config file when it is a txt file
    Args:
        SRconfig_path (str): Path to the SR config text file
    Returns:
        sr_config (dict): Dictionary containing the SR config
    """

    cfg = {}
    with open(SRconfig_path, "r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            parts = s.split()
            key = parts[0]
            value = " ".join(parts[1:])  # keep as a single string
            cfg[key] = value

    sr_config = {}
    try: sr_config["minEta"] = float(cfg["minEta"])
    except: pass
    
    try: sr_config["minPxCount"] = int(cfg["minPxCount"])
    except: pass
    
    try: sr_config["skipFitIfExists"] = str(cfg["skipFitIfExists"])
    except: pass
    
    try: sr_config["fitPeakShapePV"] = str(cfg["fitPeakShapePV"])
    except: pass
    
    try: sr_config["R_deviation"] = float(cfg["R_deviation"])
    except: pass
    
    try: sr_config["lrsz"] = int(cfg["lrsz"])
    except: pass
    
    try: sr_config["edge_bound_cutoff_fac"] = float(cfg["edge_bound_cutoff_fac"])
    except: pass
    
    try: sr_config["batch_size"] = int(cfg["batch_size"])
    except: pass

    sr_config["mods_to_use"] = {}
    for i in [2,4,8]:
        sr_config["mods_to_use"][f"SRx{i}"] = {}
        try: sr_config["mods_to_use"][f"SRx{i}"]["mod_dir"] = str(cfg[f"SRx{i}_mod_dir"])
        except: pass

        try: sr_config["mods_to_use"][f"SRx{i}"]["mod_itr"] = int(cfg[f"SRx{i}_mod_itr"])
        except: pass

    sr_config["spot_find_args"] = {}
    try: sr_config["spot_find_args"]["threshold"] = float(cfg["spot_threshold"])
    except: pass

    try: sr_config["spot_find_args"]["patch_size"] = int(cfg["spot_patch_size"])
    except: pass

    sr_config["peak_find_args"] = {}
    try: sr_config["peak_find_args"]["min_d"] = {f"SRx{i}": int(cfg[f"SRx{i}_min_d"]) for i in [1,2,4,8]}
    except: pass

    try: sr_config["peak_find_args"]["thresh_rel"] = {f"SRx{i}": float(cfg[f"SRx{i}_thresh_rel"]) for i in [1,2,4,8]}
    except: pass

    try: sr_config["peak_find_args"]["gauss_filter_sigma"] = {f"SRx{i}": float(cfg[f"SRx{i}_gauss_filter_sigma"]) for i in [1,2,4,8]}
    except: pass

    try: sr_config["peak_find_args"]["median_filter_size"] = {f"SRx{i}": int(cfg[f"SRx{i}_median_filter_size"]) for i in [1,2,4,8]}
    except: pass

    try: sr_config["peak_find_args"]["peak_crop_size"] = {f"SRx{i}": int(cfg[f"SRx{i}_peak_crop_size"]) for i in [1,2,4,8]}
    except: pass

    try: sr_config["peak_find_args"]["pvfit_int_thresh"] = {f"SRx{i}": float(cfg[f"SRx{i}_pvfit_int_thresh"]) for i in [1,2,4,8]}
    except: pass
    sr_config["shift_YZ_pos"] = {}
    for i in [2,4,8]:
        try:
            sr_config["shift_YZ_pos"][f"SRx{i}"] = {
                "shiftYpx": float(cfg[f"SRx{i}_shift_Ypx"]),
                "shiftZpx": float(cfg[f"SRx{i}_shift_Zpx"])
            }
        except: pass

    return sr_config


def update_nested_dict(dict_a, dict_b):
    """Update a nested dictionary with values from another nested dictionary
    Args:
        dict_a (dict): Dictionary to be updated
        dict_b (dict): Dictionary with values to be updated
    """
    for key, value in dict_b.items():
        if key in dict_a:
            # If both values are dictionaries, recurse
            if isinstance(dict_a[key], dict) and isinstance(value, dict):
                update_nested_dict(dict_a[key], value)
            else:
                # Update the value
                dict_a[key] = value
        else:
            # Key doesn't exist in A, add it
            dict_a[key] = value


# ----------------------------
"""When this script is called from within the ff_MIDAS_sr.py, note the following:
1) The full SR_config_path is provided to the super_res_process.py by the ff_MIDAS_sr.py script.
"""

parser = argparse.ArgumentParser(description="Routine to create SR patches & perform pseudoVoigt fit for a given MIDAS layer.\
                    The analysis take midas ZArr file as input from the directory provided")

parser.add_argument("-midasZarrDir",type=str,  help="Directory containing the Zarr file")
parser.add_argument("-srfac",       type=int,   default=8,  help="(1/2/4/8; def=8) Super-resolution factor")
parser.add_argument("-SRconfig_path", type=str,   default="sr_config.json",  help="SR config file path. If not provided, the default configration file will be used")
parser.add_argument("-midasVerDir", type=str,   default=".",  help="MIDAS version directory used to create paths to trained models")
parser.add_argument("-saveSRpatches", type=int,   default=1,   help="1: Save SR patches, 0: Do not save SR patches")
parser.add_argument("-saveFrameGoodCoords", type=int,   default=1,   help="1: Save frame goodCoords array, 0: Do not save frame goodCoords map")

args, unparsed = parser.parse_known_args()

# If the last character of the midasZarrDir is not the separator, add one
if args.midasZarrDir[-1] != SEP:
    args.midasZarrDir = args.midasZarrDir + SEP


t0 = time.time()
t_run = 0 
# Setup logging
ts = time.time()
SRlogger = setup_logging(args.midasZarrDir)
tf = time.time()
t_run += tf - ts
SRlogger.info(f"{'-'*5} Time to setup logging: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

SRlogger.info(f"Searching for MIDAS zip file in dir: {args.midasZarrDir}")
ts = time.time()
midas_zip_filename = [i for i in os.listdir(args.midasZarrDir) if ".MIDAS.zip" in i][0]
midas_zip_filepath = f"{args.midasZarrDir}{midas_zip_filename}"

tf = time.time()    
t_run += tf - ts
SRlogger.info(f"\t|Found MIDAS zip file: {midas_zip_filename}")
SRlogger.info(f"{'-'*5} Time to find MIDAS zip file: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

SRlogger.info(f"Loading Zarr file: {midas_zip_filename}")
ts = time.time()
zf= zarr.open(midas_zip_filepath,"r")

SRlogger.info(f"\t|Extracting parameters needed for super-res workflow")
zf_process_params = zf["analysis"]["process"]["analysis_parameters"]
zf_scan_params = zf["measurement/process/scan_parameters"]

sr_params = {}
sr_params["Ypx_BC"] = float(zf_process_params["YCen"][0])
sr_params["Zpx_BC"] = float(zf_process_params["ZCen"][0])
sr_params["ringsToUse"] = list(zf_process_params["RingThresh"][:][:,0].astype(int))
sr_params["ringsThresh"] = list(zf_process_params["RingThresh"][:][:,1].astype(float))
sr_params["spacegroup"] = int(zf_process_params["SpaceGroup"][0])
sr_params["lattParam"] = list(zf_process_params["LatticeParameter"][:].astype(float))
sr_params["xrayLambda"] = float(zf_process_params["Wavelength"][0]) # in Angstrom
sr_params["Lsd"] = float(zf_process_params["Lsd"][0])
sr_params["pxSize"] = float(zf_process_params["PixelSize"][0])
sr_params["tx"] = float(zf_process_params["tx"][0])
sr_params["ty"] = float(zf_process_params["ty"][0])
sr_params["tz"] = float(zf_process_params["tz"][0])
sr_params["p0"] = float(zf_process_params["p0"][0])
sr_params["p1"] = float(zf_process_params["p1"][0])
sr_params["p2"] = float(zf_process_params["p2"][0])
sr_params["p3"] = float(zf_process_params["p3"][0])
sr_params["ring_width"] = float(zf_process_params["Width"][0])
sr_params["omega_start"] = float(zf_scan_params["start"][0])
sr_params["omega_stepsize"] = float(zf_scan_params["step"][0])
sr_params["numPxY"] = int(zf["exchange"]["data"].shape[2])
sr_params["numPxZ"] = int(zf["exchange"]["data"].shape[1])

sr_params["padding"] = 6
if "Padding" in zf_process_params:
    sr_params["padding"] = int(zf_process_params["Padding"][0])

sr_params["SkipFrame"] = 0
if "SkipFrame" in zf_process_params:
    sr_params["SkipFrame"] = int(zf_process_params["SkipFrame"][0])

sr_params["ImTransOpt"] = 0
if "ImTransOpt" in zf_process_params:
    sr_params["ImTransOpt"] = int(zf_process_params["ImTransOpt"][0])

SRlogger.info(f"\t|Loading Zarr data")
exData = np.array(zf["exchange"]["data"])[sr_params["SkipFrame"]:] # Skip first 'SkipFrame' frames

del zf
tf = time.time()
t_run += tf - ts
SRlogger.info(f"\t|Nr of frames={exData.shape[0]}; after skipping {sr_params['SkipFrame']} frames")
SRlogger.info(f"{'-'*5} Time to load midas zip file: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")


SRlogger.info(f"Loading default super-resolution configuration file: {args.SRconfig_path}")
ts = time.time()

if args.SRconfig_path.endswith(".json"):
    with open(args.SRconfig_path, "r") as f:
        sr_config = json.load(f)

elif args.SRconfig_path.endswith(".txt"):
    sr_config = parse_sr_config_txt(args.SRconfig_path)

else:
    SRlogger.error(f"Invalid super-resolution configuration file: {args.SRconfig_path}.")
    SRlogger.error(f"SR config file must be a .json or .txt file.")
    sys.exit(1)


if "paramFN" in zf_process_params:
    ps_fn = zf_process_params["paramFN"][0].decode('utf-8')
    pf_fp = os.path.join(args.midasZarrDir, ps_fn)

"""Below code is used to update the SR config with the parameters from the parameter text file
# Currently disabled since the ps_fn obtained from ff_MIDAS_sr.py is not getting read correctly.

SRlogger.info(f"Updating SR config with parameters from midas parameter file: {pf_fp}")

if os.path.exists(pf_fp):
    sr_config_in_ps = parse_sr_config_txt(pf_fp)
    update_nested_dict(sr_config, sr_config_in_ps)
else:
    SRlogger.warning(f"Parameter file not found: {pf_fp}. Skipping parameter file update.")
"""

sr_config_savepath = os.path.join(args.midasZarrDir, "SR_out", "sr_config.json")
with open(sr_config_savepath, "w") as f:
    json.dump(sr_config, f, indent=4, cls=NumpyEncoder)
SRlogger.info(f"\t|Super-resolution configuration file saved to: {sr_config_savepath}")

sr_params_savepath = os.path.join(args.midasZarrDir, "SR_out", "sr_params.json")
with open(sr_params_savepath, "w") as f:
    json.dump(sr_params, f, indent=4, cls=NumpyEncoder)
SRlogger.info(f"\t|Super-resolution parameters file saved to: {sr_params_savepath}")

tf = time.time()    
t_run += tf - ts
SRlogger.info(f"{'-'*5} Time to load, update & save SR config: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

SRlogger.info(f"Reading ring positions from '{args.midasZarrDir}hkls.csv'")
ts = time.time()
df_hkls = read_hkls_csv(f"{args.midasZarrDir}hkls.csv")
rings_Rpx = (df_hkls["Radius"].unique() / sr_params["pxSize"]).tolist()

rings_to_use_Rpx = [rings_Rpx[int(i)-1] for i in (sr_params['ringsToUse'])]
sr_params["rings_to_use_Rpx"] = rings_to_use_Rpx

tf = time.time()
t_run += tf - ts
SRlogger.info(f"Ring radii (px) {rings_to_use_Rpx}")
SRlogger.info(f"{'-'*5} Time to calculate ring radii: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")


SRlogger.info(f"Creating detector RingNr map (after tilt/distortion corrections)")
ts = time.time()
RingNrmap = ringNr_map_on_detector(sr_params)
RingNrmap_savepath = os.path.join(args.midasZarrDir, "SR_out", "RingNrmap.npy")
np.save(RingNrmap_savepath, RingNrmap)
SRlogger.info(f"\t|Detector RingNr map saved to: {RingNrmap_savepath}")
tf = time.time()
t_run += tf - ts
SRlogger.info(f"{'-'*5} Time to create detector RingNr map: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

ts = time.time()
peaks_csv_dir = f"{args.midasZarrDir}Temp{SEP}"
if sr_config["skipFitIfExists"].lower() in ["no", "n", "false", "f", "0"]:
    # Delete the peaks csvfolder if it exists
    if os.path.isdir(peaks_csv_dir):
        shutil.rmtree(peaks_csv_dir)
        SRlogger.info(f"Deleted existing 'Temp' folder in MIDAS directory")
    os.mkdir(peaks_csv_dir)
    SRlogger.info(f"Created new 'Temp' folder in MIDAS directory (peaks csv files will be saved here)'")
else:
    # Create the peaks csv folder if it does not exist
    # But if it exists, do not create it again
    if not os.path.isdir(peaks_csv_dir):
        os.mkdir(peaks_csv_dir) # create new output directory
        SRlogger.info(f"Created 'Temp' folder in MIDAS directory (peaks csv files will be saved here)'")
    else:
        SRlogger.info(f"Temp folder already exists in MIDAS directory. Skipping peak fitting for frames that already have csv files.")

tf = time.time()
t_run += tf - ts
SRlogger.info(f"{'-'*5} 'Temp' directory setup completed in {tf - ts:.5f}s | SR_run_time: {t_run:.5f}s")

# Selecting the device for model training
SRlogger.info(f"Selecting the device for running ML models")
ts = time.time()

if torch.cuda.is_available():
    torch_devs = torch.device("cuda")
elif torch.backends.mps.is_available():
    torch_devs = torch.device("mps")
else:
    torch_devs = torch.device("cpu")

tf = time.time()
t_run += tf - ts
SRlogger.info(f"\t|Device selected: {torch_devs}")
SRlogger.info(f"{'-'*5} Time to select the device: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

SRlogger.info(f"Loading the trained models")
ts = time.time()
with torch.no_grad():
    x2mod, x2mod_args, x2mod_ch = load_trained_CNNSR(midasVerDir=args.midasVerDir, mod_dir=sr_config["mods_to_use"]["SRx2"]["mod_dir"], mod_itr=sr_config["mods_to_use"]["SRx2"]["mod_itr"], torch_devs=torch_devs)
    x4mod, x4mod_args,x4mod_ch = load_trained_CNNSR(midasVerDir=args.midasVerDir, mod_dir=sr_config["mods_to_use"]["SRx4"]["mod_dir"], mod_itr=sr_config["mods_to_use"]["SRx4"]["mod_itr"], torch_devs=torch_devs)
    x8mod, x8mod_args, x8mod_ch = load_trained_CNNSR(midasVerDir=args.midasVerDir, mod_dir=sr_config["mods_to_use"]["SRx8"]["mod_dir"], mod_itr=sr_config["mods_to_use"]["SRx8"]["mod_itr"], torch_devs=torch_devs)
    x2mod.eval()
    x4mod.eval()
    x8mod.eval()

tf = time.time()
t_run += tf - ts
SRlogger.info(f"\t|Models loaded in evaluation mode.")
SRlogger.info(f"{'-'*5} Time to load the models: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

SRlogger.info(f"Defining column names for the output csv files.")
# Column names for the output csv file
col_names = ["SpotID", "IntegratedIntensity", "Omega(degrees)", "YCen(px)", "ZCen(px)", "IMax",
             "Radius(px)", "Eta(degrees)", "SigmaR", "SigmaEta", "NrPixels",
             "TotalNrPixelsInPeakRegion","nPeaks", "maxY", "maxZ", "diffY", "diffZ"]

SRlogger.info(f"Calculating omega stepsize based on the number of frames in the data.")
nr_frames = exData.shape[0]

SRlogger.info(f"\t|Nr. frames={nr_frames} | Omega start={sr_params["omega_start"]} | Omega stepsize={sr_params["omega_stepsize"]}")

SRlogger.info(f"Getting Y-Z peak position pixel shift values to be used due to super-resolution factor")
shiftYpx = sr_config["shift_YZ_pos"][f"SRx{args.srfac}"]["shiftYpx"]
shiftZpx = sr_config["shift_YZ_pos"][f"SRx{args.srfac}"]["shiftZpx"]
SRlogger.info(f"\t|shiftYpx: {shiftYpx}, shiftZpx: {shiftZpx}")


for frame_i in range(0, nr_frames):
    t0_frame = time.time()
    SRlogger.info(f"{'='*60}")
    SRlogger.info(f"{'*'*5} Processing frame {frame_i} {'*'*5} ")

    frame_i_csv_savename = f"{midas_zip_filename}_{str(frame_i+1).zfill(sr_params["padding"])}_PS.csv"
    frame_i_csv_savepath = f"{peaks_csv_dir}{frame_i_csv_savename}"

    df_peaks_frame_i = pd.DataFrame(columns=col_names)

    # Skip if csv file already exists provided skipIfExists is set to 'yes'
    if sr_config["skipFitIfExists"].lower() in ["yes", "y", "true", "t", "1"] and os.path.isfile(frame_i_csv_savepath):
        SRlogger.info(f"{'*'*5}| Frame {frame_i} skipped as csv file already exists.")
        continue

    frame_arr = exData[frame_i]
    if sr_params["ImTransOpt"] != 0:
        SRlogger.info(f"\t| Image ransformation for frame {frame_i} (ImTransOpt={sr_params["ImTransOpt"]})")

    if sr_params["ImTransOpt"] == 1:
        SRlogger.info(f"\t    | Flipping image horizontally | ImTransOpt=1")
        frame_arr = np.flip(frame_arr, axis=1)

    if sr_params["ImTransOpt"] == 2:
        SRlogger.info(f"\t    | Flipping image vertically | ImTransOpt=2")
        frame_arr = np.flip(frame_arr, axis=0)

    if sr_params["ImTransOpt"] == 3:
        SRlogger.info(f"\t    | Transpose image | ImTransOpt=3")
        frame_arr = np.transpose(frame_arr)

    SRlogger.info(f"\t| Creating goodCoords map for pixels that belong to a ring and exceed the threshold for that ring")
    ts = time.time()
    frame_goodCoords = np.zeros_like(frame_arr)
    for ring_i, ring_thresh in enumerate(sr_params["ringsThresh"]):
        # Mask for pixels that belong to the current ring and exceed the threshold for that ring
        valid_pixels_mask = (RingNrmap == ring_i) & (frame_arr >= ring_thresh)
        
        # Set the goodCoords for the valid pixels to the frame_arr value for that pixel
        frame_goodCoords[valid_pixels_mask] = frame_arr[valid_pixels_mask]

    if args.saveFrameGoodCoords == 1:
        frame_goodCoords_save_dirpath = os.path.join(args.midasZarrDir, "SR_out", "frame_goodCoords")
        if not os.path.isdir(frame_goodCoords_save_dirpath):
            os.mkdir(frame_goodCoords_save_dirpath)
            SRlogger.info(f"Created 'frame_goodCoords' folder in MIDAS directory (frame goodCoords maps will be saved here)'")

        frame_goodCoords_savepath = os.path.join(frame_goodCoords_save_dirpath, f"{str(frame_i).zfill(sr_params["padding"])}_GC.npy")
        np.save(frame_goodCoords_savepath, frame_goodCoords)
        SRlogger.info(f"\t|Frame goodCoords map saved to: {frame_goodCoords_savepath}")

    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"{'-'*5} Time to create goodCoords map: {tf - ts:.5f} s | SR_run_time: {t_run:.5f} s")

    SRlogger.info(f"\t| Extracting patches using goodCoords computed from frame {frame_i}")
    ts = time.time()

    patches_exp, patches_Z00, patches_Y00, nr_pixels_in_patch = \
            patches_from_detector_frame(frame_goodCoords, sr_config, connectivity_dim=8)
    
    n_patches = len(patches_exp) # np. of patches

    if n_patches == 0:
        SRlogger.info(f"\t| No patches found in frame {frame_i}")
        df_peaks_frame_i.to_csv(frame_i_csv_savepath, sep="\t", index=False)
        continue

    patches_exp = np.expand_dims(patches_exp, axis=1) # expand dimension to make this ready as input for SR model
    patches_Isum = np.sum(patches_exp, axis=(1,2,3)).tolist()

    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"\t| Nr. of patches in frame {frame_i}: {patches_exp.shape[0]}")
    SRlogger.info(f"{'-'*5}Time to extract patches: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")


    SRlogger.info(f"\t| Upscaling experimental patches to create inputfor SRx2")
    ts = time.time()
    upscale_fac = 2
    patches_subset = patches_exp[:, x2mod_ch, :, :] # Extract only the channels we need
    upscaled_patches = np.repeat(np.repeat(patches_subset, upscale_fac, axis=2), upscale_fac, axis=3)
    upscaled_patches = upscaled_patches / (upscale_fac * upscale_fac) # Scale by upscale factor squared
    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"{'-'*5}Time to create upscaled patches for SRx2 input: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")

    SRlogger.info(f"\t| Normalizing upscaled input SRx2 patches")
    ts = time.time()
    max_vals = np.max(upscaled_patches, axis=(2, 3), keepdims=True)
    max_vals = np.where(max_vals == 0, 1, max_vals)  # Avoid division by zero
    Xin_x2 = upscaled_patches / max_vals
    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"{'-'*5}Time to normalize SRx2 input: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")


    SRlogger.info(f"\t| Running inference: SRx2 model")
    ts = time.time()
    n_batches = n_patches // sr_config["batch_size"]

    # Running SRx2 predictions in batches
    with torch.no_grad():
        for i in range(0, n_batches+1):
            i_s, i_f = i * sr_config["batch_size"], (min((i+1)*sr_config["batch_size"], n_patches))
            if i_s < n_patches:
                X_batch = Xin_x2[i_s:i_f]
                X_batch = torch.from_numpy(X_batch.astype(np.float32))
                X_batch = X_batch.to(torch_devs)
                SRx2_pred_batch = x2mod.forward(X_batch).detach().cpu().numpy()

                if i == 0:SRx2_pred = deepcopy(SRx2_pred_batch)
                else: SRx2_pred = np.append(SRx2_pred, SRx2_pred_batch, axis=0)

    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"{'-'*5} Time to predict SRx2 patches: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")


    if args.srfac > 2.5:
        SRlogger.info(f"\t| Upscaling SRx2 predicted patches to create input for SRx4 model")
        ts = time.time()
        upscale_fac = 2
        patches_subset = SRx2_pred[:, x4mod_ch, :, :] # Extract only the channels we need
        upscaled_patches = np.repeat(np.repeat(patches_subset, upscale_fac, axis=2), upscale_fac, axis=3)
        upscaled_patches = upscaled_patches / (upscale_fac * upscale_fac) # Scale by upscale factor squared
        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5} Time to create upscaled patches for SRx4 input: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")
        
        SRlogger.info(f"\t| Normalizing upscaled input SRx4 patches")
        ts = time.time()
        max_vals = np.max(upscaled_patches, axis=(2, 3), keepdims=True)
        max_vals = np.where(max_vals == 0, 1, max_vals)  # Avoid division by zero
        Xin_x4 = upscaled_patches / max_vals
        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5}Time to normalize SRx4 input: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")

        SRlogger.info(f"\t| Running inference: SRx4 model")
        ts = time.time()

        # Running SRx4 predictions in batches
        with torch.no_grad():
            for i in range(0, n_batches+1):
                i_s, i_f = i * sr_config["batch_size"], (min((i+1)*sr_config["batch_size"], n_patches))
                if i_s < n_patches:
                    X_batch = Xin_x4[i_s:i_f]
                    X_batch = torch.from_numpy(X_batch.astype(np.float32))
                    X_batch = X_batch.to(torch_devs)
                    SRx4_pred_batch = x4mod.forward(X_batch).detach().cpu().numpy()

                    if i == 0:
                        SRx4_pred = deepcopy(SRx4_pred_batch)
                    else:
                        SRx4_pred = np.append(SRx4_pred, SRx4_pred_batch, axis=0)

        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5} Time to predict SRx4 patches: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")


    if args.srfac > 4.5:
        SRlogger.info(f"\t| Upscaling SRx4 predicted patches to create input for SRx8 model")
        ts = time.time()
        upscale_fac = 2
        patches_subset = SRx4_pred[:, x8mod_ch, :, :] # Extract only the channels we need
        upscaled_patches = np.repeat(np.repeat(patches_subset, upscale_fac, axis=2), upscale_fac, axis=3)
        upscaled_patches = upscaled_patches / (upscale_fac * upscale_fac) # Scale by upscale factor squared
        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5} Time to create upscaled patches for SRx8 input: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")
        
        SRlogger.info(f"\t| Normalizing upscaled input SRx8 patches")
        ts = time.time()
        max_vals = np.max(upscaled_patches, axis=(2, 3), keepdims=True)
        max_vals = np.where(max_vals == 0, 1, max_vals)  # Avoid division by zero
        Xin_x8 = upscaled_patches / max_vals
        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5} Time to normalize SRx8 input: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")


        SRlogger.info(f"\t| Running inference: SRx8 model")
        ts = time.time()

        # Running SRx8 predictions
        # Use autocast if cuda-GPU is available
        if torch_devs.type == "cuda":
            with torch.no_grad(), autocast(torch_devs.type):
                for i in range(0, n_batches+1):
                    i_s, i_f = i * sr_config["batch_size"], (min((i+1)*sr_config["batch_size"], n_patches))
                    if i_s < n_patches:
                        X_batch = Xin_x8[i_s:i_f]
                        X_batch = torch.from_numpy(X_batch.astype(np.float32))
                        X_batch = X_batch.to(torch_devs)
                        #SRx8_pred_batch = x8mod.forward(X_batch).detach().cpu().numpy()
                        SRx8_pred_batch = x8mod.forward(X_batch)
                        current_sums = torch.sum(SRx8_pred_batch, dim=(1, 2, 3))  # Shape: [248]
                        batch_target_sums = patches_Isum[i_s:i_f] 
                        target_sums = torch.tensor(batch_target_sums, device=SRx8_pred_batch.device)
                        scaling_factors = target_sums / current_sums
                        scaling_factors = scaling_factors.view(-1, 1, 1, 1)
                        SRx8_pred_batch = SRx8_pred_batch * scaling_factors
                        SRx8_pred_batch = SRx8_pred_batch.detach().cpu().numpy()

                        if i == 0:
                            SRx8_pred = deepcopy(SRx8_pred_batch)
                        else:
                            SRx8_pred = np.append(SRx8_pred, SRx8_pred_batch, axis=0)

        # Run SRx8 predictions without autocast if cuda is not available
        if torch_devs.type != "cuda":
            with torch.no_grad():
                for i in range(0, n_batches+1):
                    i_s, i_f = i * sr_config["batch_size"], (min((i+1)*sr_config["batch_size"], n_patches))
                    if i_s < n_patches:
                        X_batch = Xin_x8[i_s:i_f]
                        X_batch = torch.from_numpy(X_batch.astype(np.float32))
                        X_batch = X_batch.to(torch_devs)
                        #SRx8_pred_batch = x8mod.forward(X_batch).detach().cpu().numpy()
                        SRx8_pred_batch = x8mod.forward(X_batch)
                        current_sums = torch.sum(SRx8_pred_batch, dim=(1, 2, 3))  # Shape: [248]
                        batch_target_sums = patches_Isum[i_s:i_f] 
                        target_sums = torch.tensor(batch_target_sums, device=SRx8_pred_batch.device)
                        scaling_factors = target_sums / current_sums
                        scaling_factors = scaling_factors.view(-1, 1, 1, 1)
                        SRx8_pred_batch = SRx8_pred_batch * scaling_factors
                        SRx8_pred_batch = SRx8_pred_batch.detach().cpu().numpy()

                        if i == 0:
                            SRx8_pred = deepcopy(SRx8_pred_batch)
                        else:
                            SRx8_pred = np.append(SRx8_pred, SRx8_pred_batch, axis=0)


        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5} Time to predict SRx8 patches: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")

    # Based on srfac value, decide which patches will be used for peak analysis
    if args.srfac==2:
        patches_to_fit = SRx2_pred
        SRlogger.info(f"\t| Using SRx2 predicted patches for peak analysis")
    if args.srfac==4:
        patches_to_fit = SRx4_pred
        SRlogger.info(f"\t| Using SRx4 predicted patches for peak analysis")
    if args.srfac==8:
        patches_to_fit = SRx8_pred
        SRlogger.info(f"\t| Using SRx8 predicted patches for peak analysis")

    
    # Save SR patches to disk
    if args.saveSRpatches == 1:

        SR_patch_save_dirpath = f"{args.midasZarrDir}SR_out{SEP}SR_patches{SEP}"
        if not os.path.isdir(SR_patch_save_dirpath):
            os.mkdir(SR_patch_save_dirpath) # create new output directory
            SRlogger.info(f"Created 'SR_out/SR_patches/' folder in MIDAS directory (SR patches will be saved here)'")
        else:
            SRlogger.info(f"SR_out/SR_patches/ folder already exists in MIDAS directory")

        SRlogger.info(f"\t| Saving SR patches to disk: {SR_patch_save_dirpath}")

        ts = time.time()
        np.save(f"{SR_patch_save_dirpath}{str(frame_i).zfill(sr_params["padding"])}_SRx1_exp.npy", patches_exp)
        np.save(f"{SR_patch_save_dirpath}{str(frame_i).zfill(sr_params["padding"])}_SRx2_pred.npy", SRx2_pred)
        np.save(f"{SR_patch_save_dirpath}{str(frame_i).zfill(sr_params["padding"])}_SRx4_pred.npy", SRx4_pred)
        np.save(f"{SR_patch_save_dirpath}{str(frame_i).zfill(sr_params["padding"])}_SRx8_pred.npy", SRx8_pred)

        tf = time.time()
        t_run += tf - ts
        SRlogger.info(f"{'-'*5} Time to save SR patches to disk: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")

    ts = time.time()
    spotID = int(0)
    orig_frame_index = frame_i + sr_params["SkipFrame"]
    omega = sr_params["omega_start"] + (sr_params["omega_stepsize"] * orig_frame_index)

    SRlogger.info(f"\t| Initiating peak fitting process for frame {frame_i}")
    if str(sr_config["fitPeakShapePV"]).lower() in ["no", "n", "false", "f", "0"]:
        SRlogger.info(f"\t    |Pseudo-voigt fitting DISABLED. Peak positions will be fitted with center of mass algorithm + watershed")
    if str(sr_config["fitPeakShapePV"]).lower() in ["yes", "y", "true", "t", "1"]:
        SRlogger.info(f"\t    |Pseudo-voigt fitting ENABLED.")
    if str(sr_config["fitPeakShapePV"]).lower() in ["auto", "partial", "mix"]:
        SRlogger.info(f"\t    |If multiple peaks in patch: Use pseudo-Voigt fit. If single peak: Use center of mass algorithm + watershed")
    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"{'-'*5} Time to initiate peak fitting process for frame {frame_i}: {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")

    ts = time.time()
    # Get Radius values for all patches in the frame
    R_patches = np.sqrt((sr_params["Ypx_BC"] - (np.array(patches_Y00) + sr_config["spot_find_args"]["patch_size"]/2))**2 +
                        (sr_params["Zpx_BC"] - (np.array(patches_Z00) + sr_config["spot_find_args"]["patch_size"]/2))**2)

    n_peaks_in_patches_list = []
    for patch_i in range(len(patches_to_fit)):
        patch = patches_to_fit[patch_i, 0]
        Z00, Y00 = patches_Z00[patch_i], patches_Y00[patch_i]

        patch_for_locmax = gaussian_filter(patch, sigma=sr_config["peak_find_args"]["gauss_filter_sigma"][f"SRx{args.srfac}"])
        patch_for_locmax = median_filter(patch_for_locmax, size=sr_config["peak_find_args"]["median_filter_size"][f"SRx{args.srfac}"])

        locmax_peak_coords = peak_local_max(patch_for_locmax,
                                                min_distance=sr_config["peak_find_args"]["min_d"][f"SRx{args.srfac}"],
                                                threshold_rel=sr_config["peak_find_args"]["thresh_rel"][f"SRx{args.srfac}"])
            
        n_peaks_in_patch = len(locmax_peak_coords)
        n_peaks_in_patches_list.append(n_peaks_in_patch)
        
        if (str(sr_config["fitPeakShapePV"]).lower() in ["no", "n", "false", "f", "0"]) or\
            (str(sr_config["fitPeakShapePV"]).lower() in ["auto", "partial", "mix"] and n_peaks_in_patch == 1):

            # Cutting off peaks that are too close to the edges of the patch
            bnd_peak_cutoff = sr_config["edge_bound_cutoff_fac"] * args.srfac
            locmax_peak_coords = locmax_peak_coords[~(locmax_peak_coords[:,:]<bnd_peak_cutoff).any(1)]
            locmax_peak_coords = locmax_peak_coords[~(locmax_peak_coords[:,:]>((sr_config["lrsz"] * args.srfac)-bnd_peak_cutoff)).any(1)]
            
            com_coords = com_peak_coords(patch, locmax_peak_coords,
                                            threshold=0.7,
                                            peak_crop_size=sr_config["peak_find_args"]["peak_crop_size"][f"SRx{args.srfac}"])

            # Apply watershed algorithm to allocate regions
            # Thresh for mask should be same as the threshold used to find local maxima
            # otherwise, watershed may end up ignoring a peak
            labelled_patch, peak_label_values, peaks_Isum, peaks_NrPixels = \
                watershed_peaks(patch, locmax_peak_coords,
                                mask_thresh=sr_config["peak_find_args"]["thresh_rel"][f"SRx{args.srfac}"])

            n_peaks_in_patch_after_ws = len(com_coords)
            for (peak_i, peak_label) in zip(range(n_peaks_in_patch_after_ws), peak_label_values):
                spotID += 1

                # Segment out the current peak from the patch
                peak_i_patch = patch * (labelled_patch == peak_label)

                #---------------------------
                # Downscale the peak patch to SRx1
                downscale_fac = int(args.srfac / 1) # downscale factor: number of pixels (in each direction) in input patch per pixel in downscaled image
                h, w = peak_i_patch.shape
                new_h, new_w = h // downscale_fac, w // downscale_fac # Reshape input to group pixels for pooling

                # Reshape and sum using vectorized operations
                reshaped = peak_i_patch[:new_h * downscale_fac, :new_w * downscale_fac].reshape(
                    new_h, downscale_fac, new_w, downscale_fac)
                
                peak_i_patch_SRx1 = np.sum(reshaped, axis=(1, 3))
                #-------

                IntegratedIntensity = np.sum(peak_i_patch_SRx1)
                NrPixels = np.count_nonzero(peak_i_patch_SRx1 > 1E-2)
                IMax = np.max(peak_i_patch_SRx1)
                TotalNrPixelsInPeakRegion = nr_pixels_in_patch[patch_i]

                # Get peak position in detector frame pixels
                YCen_px = Y00 + (com_coords[peak_i][1] * (1/args.srfac)) + float(shiftYpx)
                ZCen_px = Z00 + (com_coords[peak_i][0] * (1/args.srfac)) + float(shiftZpx)
                
                # Get peak R & Eta values from Y & Z positions
                R = math.sqrt((sr_params["Ypx_BC"] - YCen_px)**2 + (sr_params["Zpx_BC"] - ZCen_px)**2)
                Eta = math.degrees(math.acos((ZCen_px - sr_params["Zpx_BC"]) / R))
                
                # Convert Eta_inDeg to -ve where Ypx < Ypx_BC
                Eta = Eta * ((YCen_px - sr_params["Ypx_BC"]) / np.abs(YCen_px - sr_params["Ypx_BC"]))
            
                SigmaR, SigmaEta = 1, 1 # default sigma values

                # Get max Y & Z positions in SRx1 detector frame pixels
                r_max_SRx1, c_max_SRx1 = np.unravel_index(np.argmax(peak_i_patch_SRx1), peak_i_patch_SRx1.shape)  # (row, col)
                maxY = Y00 + c_max_SRx1
                maxZ = Z00 + r_max_SRx1
                # Get difference values between peak positions in SRx1 and MIDAS detector frames
                diffY = maxY - YCen_px
                diffZ = maxZ - ZCen_px

                peak_data = [spotID, IntegratedIntensity, omega, YCen_px, ZCen_px, IMax, R, Eta, SigmaR, SigmaEta, NrPixels, TotalNrPixelsInPeakRegion, n_peaks_in_patch, maxY, maxZ, diffY, diffZ]

                # Add to peaks dataframe only if Eta is within the range of minEta and if the number of pixels is greated than the minimum needed for a peak
                df_peaks_frame_i.loc[spotID-1] = peak_data


        if (str(sr_config["fitPeakShapePV"]).lower() in ["yes", "y", "true", "t", "1"]) or\
            (str(sr_config["fitPeakShapePV"]).lower() in ["auto", "partial", "mix"] and n_peaks_in_patch >= 2):

            try:
                # Perform peak fitting on the patch to get peak parameters
                pvfit_peaks, _, _ = multi_pv_fit(patch, patches_Y00[patch_i], patches_Z00[patch_i],
                                    sr_params["Ypx_BC"], sr_params["Zpx_BC"], sr_config["lrsz"], args.srfac,
                                    min_distance=sr_config["peak_find_args"]["min_d"][f"SRx{args.srfac}"],
                                    threshold_rel=sr_config["peak_find_args"]["thresh_rel"][f"SRx{args.srfac}"],
                                    gauss_filter_sigma=sr_config["peak_find_args"]["gauss_filter_sigma"][f"SRx{args.srfac}"],
                                    median_filter_size=sr_config["peak_find_args"]["median_filter_size"][f"SRx{args.srfac}"],
                                    lr_int_thresh=sr_config["peak_find_args"]["pvfit_int_thresh"][f"SRx{args.srfac}"])
                
                n_peaks_in_patch = len(pvfit_peaks)
                for peak_i in range(n_peaks_in_patch):
                    
                    spotID += 1
                    peak_prop = pvfit_peaks[peak_i]
                    R, Eta = peak_prop["R(px)"], peak_prop["Eta(deg)"]
                    
                    # Create RR and EE spread over the patch
                    dpx_sr = 1 / args.srfac # pixel step size in super-res patch

                    # Y-Z coordinate values
                    Ypx = np.arange(Y00, Y00 + sr_config["spot_find_args"]["patch_size"], dpx_sr)
                    Zpx = np.arange(Z00, Z00 + sr_config["spot_find_args"]["patch_size"], dpx_sr)

                    # Create meshgrids of Radius and Eta values
                    grid_YY, grid_ZZ = np.meshgrid(Ypx, Zpx)
                    grid_RR = ((sr_params["Ypx_BC"] - grid_YY)**2 + (sr_params["Zpx_BC"] - grid_ZZ)**2)**0.5
                    grid_EE = np.rad2deg(np.arccos((grid_ZZ - sr_params["Zpx_BC"]) / grid_RR))
                    # Convert Eta_inDeg to -ve where Ypx < Ypx_BC
                    grid_EE = grid_EE * ((grid_YY - sr_params["Ypx_BC"]) / np.abs(grid_YY - sr_params["Ypx_BC"]))

                    peak_fit_patch = pseudoVoigt2d_diffLGwidth(grid_RR, grid_EE,
                                            y0=R, z0=Eta,
                                            ySigG=peak_prop["SigGR"], zSigG=peak_prop["SigGEta"],
                                            ySigL=peak_prop["SigLR"], zSigL=peak_prop["SigLEta"],
                                            LGmix=peak_prop["LGmix"], IMax=peak_prop["IMax"])
                    
                    #---------------------------
                    # Downscale the peak patch to SRx1
                    downscale_fac = int(args.srfac / 1) # downscale factor: number of pixels (in each direction) in input patch per pixel in downscaled image
                    h, w = peak_fit_patch.shape
                    new_h, new_w = h // downscale_fac, w // downscale_fac # Reshape input to group pixels for pooling

                    # Reshape and sum using vectorized operations
                    reshaped = peak_fit_patch[:new_h * downscale_fac, :new_w * downscale_fac].reshape(
                        new_h, downscale_fac, new_w, downscale_fac)
                    
                    peak_fit_patch_SRx1 = np.sum(reshaped, axis=(1, 3))
                    #-------

                    r_max_SRx1, c_max_SRx1 = np.unravel_index(np.argmax(peak_fit_patch_SRx1), peak_fit_patch_SRx1.shape)  # (row, col)
                    maxY = Y00 + c_max_SRx1
                    maxZ = Z00 + r_max_SRx1

                    IntegratedIntensity = np.sum(peak_fit_patch)
                    YCen_px = peak_prop["Y(px)"] + shiftYpx
                    ZCen_px = peak_prop["Z(px)"] + shiftZpx
                    IMax = np.max(peak_fit_patch_SRx1)
                    SigmaR = max(peak_prop["SigGR"], peak_prop["SigLR"])
                    SigmaEta = max(peak_prop["SigGEta"], peak_prop["SigLEta"])
                    NrPixels = np.count_nonzero(peak_fit_patch_SRx1 * patches_exp[patch_i])
                    TotalNrPixelsInPeakRegion = nr_pixels_in_patch[patch_i]

                    diffY = maxY - YCen_px
                    diffZ = maxZ - ZCen_px
                    peak_data = [spotID, IntegratedIntensity, omega, YCen_px, ZCen_px, IMax, R, Eta, SigmaR, SigmaEta, NrPixels, TotalNrPixelsInPeakRegion, n_peaks_in_patch, maxY, maxZ, diffY, diffZ]

                    df_peaks_frame_i.loc[spotID-1] = peak_data

            except Exception as e:
                SRlogger.warning(f"\tFrame {frame_i}: Patch {patch_i} skipped as pseudoVoigt fit did not converge. Error: {e}") 
    
    tf = time.time()
    t_run += tf - ts
    SRlogger.info(f"{'-'*5} Time to fit peaks (frame {frame_i}): {tf - ts:.5f} s | frame_time: {tf - t0_frame:.5f} s | SR_run_time: {t_run:.5f} s")

    if args.saveSRpatches == 1:
        patches_info_fp = f"{SR_patch_save_dirpath}{str(frame_i).zfill(sr_params["padding"])}_patches_info.csv"
        patches_info_df = pd.DataFrame({
            "Y00": patches_Y00,
            "Z00": patches_Z00,
            "nr_pixels_in_patch": nr_pixels_in_patch,
            "patches_Isum": patches_Isum,
            "n_peaks_in_patches": n_peaks_in_patches_list
        })
        patches_info_df.to_csv(patches_info_fp)
        SRlogger.info(f"\t| Saved SR patches information: {patches_info_fp}")


    df_peaks_frame_i.to_csv(frame_i_csv_savepath, sep="\t", index=False)