"""I/O utilities: JSON encoder, logging setup, hkls reader, SR config parsers.

Canonical source: SR-MIDAS/super_res_process.py
"""

import json
import logging
import datetime
import os
import shutil

import numpy as np
import pandas as pd

SEP = os.sep


# ----------------------------
class NumpyEncoder(json.JSONEncoder):
    """JSON encoder that handles numpy integer, float, and ndarray types."""

    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NumpyEncoder, self).default(obj)


# ----------------------------
def setup_logging(resultDir):
    """Setup logging configuration with timestamped log file.
    Args:
        resultDir (str): Path to the result directory (SR_out/ subdirectory is created here)
    Returns:
        logger (logging.Logger): Logger object
    """

    log_dir = f"{resultDir}SR_out{SEP}"
    if os.path.exists(log_dir):
        shutil.rmtree(log_dir)
    os.makedirs(log_dir)

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    log_filepath = f"{log_dir}SR_logs_{timestamp}.log"

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(message)s',
        handlers=[
            logging.FileHandler(log_filepath),
            logging.StreamHandler()
        ]
    )

    logger = logging.getLogger(__name__)
    logger.info(f"Logging initialized. Log filepath: {log_filepath}")
    return logger


# ----------------------------
def read_hkls_csv(hkls_csv_path):
    """Read the hkls.csv file generated by MIDAS.
    Args:
        hkls_csv_path (str): path to the hkls.csv file
    Returns:
        df_hkls (pandas dataframe): dataframe with hkls data
    """

    df_hkls = pd.read_csv(hkls_csv_path, sep=' ')
    return df_hkls


# ----------------------------
def parse_sr_config_txt(SRconfig_path):
    """Parse the SR config file when it is a txt file.
    Args:
        SRconfig_path (str): Path to the SR config text file
    Returns:
        sr_config (dict): Dictionary containing the SR config
    """

    cfg = {}
    with open(SRconfig_path, "r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            parts = s.split()
            key = parts[0]
            value = " ".join(parts[1:])
            cfg[key] = value

    sr_config = {}
    try: sr_config["minEta"] = float(cfg["minEta"])
    except: pass

    try: sr_config["minPxCount"] = int(cfg["minPxCount"])
    except: pass

    try: sr_config["skipFitIfExists"] = str(cfg["skipFitIfExists"])
    except: pass

    try: sr_config["fitPeakShapePV"] = str(cfg["fitPeakShapePV"])
    except: pass

    try: sr_config["R_deviation"] = float(cfg["R_deviation"])
    except: pass

    try: sr_config["lrsz"] = int(cfg["lrsz"])
    except: pass

    try: sr_config["edge_bound_cutoff_fac"] = float(cfg["edge_bound_cutoff_fac"])
    except: pass

    try: sr_config["batch_size"] = int(cfg["batch_size"])
    except: pass

    sr_config["mods_to_use"] = {}
    for i in [2, 4, 8]:
        sr_config["mods_to_use"][f"SRx{i}"] = {}
        try: sr_config["mods_to_use"][f"SRx{i}"]["mod_dir"] = str(cfg[f"SRx{i}_mod_dir"])
        except: pass
        try: sr_config["mods_to_use"][f"SRx{i}"]["mod_itr"] = int(cfg[f"SRx{i}_mod_itr"])
        except: pass

    sr_config["spot_find_args"] = {}
    try: sr_config["spot_find_args"]["threshold"] = float(cfg["spot_threshold"])
    except: pass
    try: sr_config["spot_find_args"]["patch_size"] = int(cfg["spot_patch_size"])
    except: pass

    sr_config["peak_find_args"] = {}
    try: sr_config["peak_find_args"]["min_d"] = {f"SRx{i}": int(cfg[f"SRx{i}_min_d"]) for i in [1, 2, 4, 8]}
    except: pass
    try: sr_config["peak_find_args"]["thresh_rel"] = {f"SRx{i}": float(cfg[f"SRx{i}_thresh_rel"]) for i in [1, 2, 4, 8]}
    except: pass
    try: sr_config["peak_find_args"]["gauss_filter_sigma"] = {f"SRx{i}": float(cfg[f"SRx{i}_gauss_filter_sigma"]) for i in [1, 2, 4, 8]}
    except: pass
    try: sr_config["peak_find_args"]["median_filter_size"] = {f"SRx{i}": int(cfg[f"SRx{i}_median_filter_size"]) for i in [1, 2, 4, 8]}
    except: pass
    try: sr_config["peak_find_args"]["peak_crop_size"] = {f"SRx{i}": int(cfg[f"SRx{i}_peak_crop_size"]) for i in [1, 2, 4, 8]}
    except: pass
    try: sr_config["peak_find_args"]["pvfit_int_thresh"] = {f"SRx{i}": float(cfg[f"SRx{i}_pvfit_int_thresh"]) for i in [1, 2, 4, 8]}
    except: pass

    sr_config["shift_YZ_pos"] = {}
    for i in [2, 4, 8]:
        try:
            sr_config["shift_YZ_pos"][f"SRx{i}"] = {
                "shiftYpx": float(cfg[f"SRx{i}_shift_Ypx"]),
                "shiftZpx": float(cfg[f"SRx{i}_shift_Zpx"])
            }
        except: pass

    return sr_config


# ----------------------------
def update_nested_dict(dict_a, dict_b):
    """Update a nested dictionary with values from another nested dictionary.
    Args:
        dict_a (dict): Dictionary to be updated (modified in place)
        dict_b (dict): Dictionary with values to update from
    """
    for key, value in dict_b.items():
        if key in dict_a:
            if isinstance(dict_a[key], dict) and isinstance(value, dict):
                update_nested_dict(dict_a[key], value)
            else:
                dict_a[key] = value
        else:
            dict_a[key] = value
